export type Categorie =
  | "Démographie"
  | "Social & Éducation"
  | "Emploi & Activité"
  | "Économie"
  | "Territoire & Urbain"
  | "Accidents & Mobilité"
  | "Environnement";

export interface Fiche {
  key: string;
  titre: string;
  sousTitre?: string;
  categorie: Categorie;
  theme: string;
  sousTheme?: string;
  source: string;
  annee: string;
  logiciel?: string;
  auteur?: string;
  typeRepresentation: string;
  classification?: string;
  variableRepresentee?: string;
  natureInformation?: string;
  constructionIndice?: string;
  formule?: string;
  methodDiscretisation?: string;
  nombreClasses?: number;
  classesValeurs?: string;
  statsDescriptives?: string;
  messagePrincipal: string;
  limites?: string;
  imageFilename: string;
}

export const FICHES: Fiche[] = [
  // ─── DÉMOGRAPHIE ───────────────────────────────────────────────────────────
  {
    key: "pop_totale_chomage",
    titre: "Population totale et taux de chômage par province",
    categorie: "Démographie",
    theme: "Démographie générale",
    sousTheme: "Répartition spatiale de la population et chômage",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte choroplèthe + cercles proportionnels",
    variableRepresentee: "Population totale (taille des cercles) · Taux de chômage (couleur)",
    natureInformation: "Quantitative absolue + relative",
    messagePrincipal:
      "Casablanca concentre la plus grande population de la région avec plus de 3,7 millions d'habitants. Les taux de chômage les plus élevés se retrouvent dans les provinces urbaines denses, contrastant avec les zones rurales de Settat et Sidi Bennour.",
    imageFilename: "Population totale et taux de chômage.jpg",
  },
  {
    key: "pop_rurale",
    titre: "Population rurale par province",
    categorie: "Démographie",
    theme: "Démographie générale",
    sousTheme: "Structure spatiale urbaine/rurale",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Part de la population rurale (%)",
    natureInformation: "Quantitative relative",
    messagePrincipal:
      "Sidi Bennour et Settat affichent les taux de ruralité les plus élevés de la région (>50%). En revanche, les préfectures de Casablanca, Nouaceur et Médiouna sont quasi exclusivement urbaines.",
    imageFilename: "Population rurale par province.jpg",
  },
  {
    key: "pop_urbaine_rurale",
    titre: "Population urbaine vs rurale",
    categorie: "Démographie",
    theme: "Démographie générale",
    sousTheme: "Comparaison urbain/rural",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS / Philcarto",
    typeRepresentation: "Carte en barres ou diagrammes comparatifs",
    variableRepresentee: "Population urbaine · Population rurale",
    natureInformation: "Quantitative absolue comparée",
    messagePrincipal:
      "La région Casablanca-Settat est l'une des plus urbanisées du Maroc. Le déséquilibre urbain/rural est maximal à Casablanca et Mohammedia, tandis que Sidi Bennour reste majoritairement rurale.",
    imageFilename: "Population urbaine vs rurale.jpg",
  },
  {
    key: "taux_urbanisation",
    titre: "Taux d'urbanisation par province",
    categorie: "Démographie",
    theme: "Démographie générale",
    sousTheme: "Niveau d'urbanisation territoriale",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux d'urbanisation (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le taux d'urbanisation régional dépasse 80%, bien au-dessus de la moyenne nationale (~62%). Casablanca, Mohammedia et Nouaceur atteignent des taux proches de 100%, reflétant la forte métropolisation du littoral atlantique.",
    imageFilename: "C02_Tx_urbanisation.jpg",
  },
  {
    key: "menages_taille",
    titre: "Nombre de ménages et taille moyenne",
    categorie: "Démographie",
    theme: "Démographie des ménages",
    sousTheme: "Structure des ménages et taille moyenne",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS / Philcarto",
    typeRepresentation: "Carte choroplèthe + cercles proportionnels",
    variableRepresentee: "Nombre de ménages (cercles) · Taille moyenne (couleur)",
    natureInformation: "Quantitative absolue + relative",
    messagePrincipal:
      "Le nombre de ménages est très concentré dans la préfecture de Casablanca. La taille moyenne des ménages est plus élevée dans les zones rurales (Sidi Bennour, Settat), indiquant des structures familiales plus larges.",
    imageFilename: "Nb_menages_tot et Taille_moy_tot.jpg",
  },
  {
    key: "pop_classif_urb",
    titre: "Population totale et classification urbaine",
    categorie: "Démographie",
    theme: "Démographie générale",
    sousTheme: "Classification territoriale et peuplement",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "Philcarto, Inkscape",
    typeRepresentation: "Carte choroplèthe + cercles proportionnels",
    variableRepresentee: "Population totale (cercles) · Classification urbaine (couleur)",
    natureInformation: "Quantitative absolue + qualitative nominale",
    messagePrincipal:
      "La carte met en évidence la macrocéphalie urbaine de Casablanca par rapport aux autres provinces. Elle illustre la classification territoriale (urbain dense, périurbain, rural) et les disparités de peuplement au sein de la région.",
    imageFilename: "ChoroPropo[Pop_tot][Classif_urb].emf.jpg",
  },

  // ─── SOCIAL & ÉDUCATION ────────────────────────────────────────────────────
  {
    key: "analphabetisme",
    titre: "Taux d'analphabétisme par province",
    categorie: "Social & Éducation",
    theme: "Éducation — Niveau d'instruction",
    sousTheme: "Taux d'analphabétisme territorial",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux d'analphabétisme (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le taux d'analphabétisme est inversement corrélé à l'urbanisation : les provinces rurales de Sidi Bennour et Settat présentent les taux les plus élevés (>30%). Casablanca affiche les taux les plus bas grâce à sa concentration d'infrastructures éducatives.",
    imageFilename: "C03—Taux d'analphabétisme.jpg",
  },
  {
    key: "ipm_pauvrete",
    titre: "Indice de Pauvreté Multidimensionnelle (IPM)",
    categorie: "Social & Éducation",
    theme: "Social — Pauvreté et exclusion",
    sousTheme: "Indice composite de pauvreté multidimensionnelle",
    source: "HCP — Enquête sur la pauvreté",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    classification: "Carte de synthèse — indice composite",
    variableRepresentee: "IPM composite (éducation, santé, niveau de vie)",
    natureInformation: "Quantitative relative ordonnée (indice composite)",
    methodDiscretisation: "Discrétisation par seuils naturels",
    messagePrincipal:
      "L'IPM révèle de profondes disparités territoriales. Les provinces rurales accumulent des privations dans les trois dimensions (éducation, santé, revenu), tandis que Casablanca et ses préfectures proches bénéficient des meilleures conditions de vie de la région.",
    imageFilename: "C04 IPM Pauvreté.jpg",
  },
  {
    key: "niveau_etude",
    titre: "Niveau d'éducation par province",
    categorie: "Social & Éducation",
    theme: "Éducation — Niveau d'instruction",
    sousTheme: "Niveau d'éducation supérieur",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Part de la population avec niveau secondaire ou supérieur (%)",
    natureInformation: "Quantitative relative",
    messagePrincipal:
      "Le niveau d'éducation est fortement polarisé autour de Casablanca et Mohammedia, qui concentrent l'essentiel des diplômés de l'enseignement supérieur. Les écarts avec les zones rurales restent importants, reflétant des inégalités d'accès à l'éducation persistantes.",
    imageFilename: "Niveau d'étude.jpg",
  },
  {
    key: "logement_proprietaires",
    titre: "Propriétaires de logement par province",
    categorie: "Social & Éducation",
    theme: "Social — Habitat et logement",
    sousTheme: "Taux de propriété immobilière",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux de propriété du logement (%)",
    natureInformation: "Quantitative relative",
    messagePrincipal:
      "Le taux de propriété est paradoxalement plus élevé dans les zones rurales où les coûts immobiliers sont faibles. À Casablanca, la location et l'habitat collectif dominent, avec moins de 50% de propriétaires dans certains arrondissements denses.",
    imageFilename: "Propriétaires logement.jpg",
  },
  {
    key: "langues",
    titre: "Langues parlées dans la région",
    categorie: "Social & Éducation",
    theme: "Social — Culture et linguistique",
    sousTheme: "Répartition des langues parlées",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS / Philcarto",
    typeRepresentation: "Carte en diagrammes (camemberts)",
    variableRepresentee: "Répartition des langues parlées par province",
    natureInformation: "Quantitative relative (proportions)",
    messagePrincipal:
      "Le darija (arabe dialectal) domine dans l'ensemble de la région. L'amazighe est plus présent dans les provinces rurales du sud. Le français garde une forte présence fonctionnelle dans les milieux urbains de Casablanca et Mohammedia.",
    imageFilename: "Langues parlees.jpg",
  },

  // ─── EMPLOI & ACTIVITÉ ─────────────────────────────────────────────────────
  {
    key: "chomage_general",
    titre: "Taux de chômage par province",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Taux de chômage territorial",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux de chômage (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le chômage est structurellement plus élevé dans les préfectures urbaines denses. Casablanca et Mohammedia enregistrent les taux les plus élevés malgré une forte activité économique, révélant un marché du travail sous tension et un chômage de masse urbain.",
    imageFilename: "Taux de chômage.jpg",
  },
  {
    key: "chomage_feminin",
    titre: "Taux de chômage féminin par province",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Chômage féminin et inégalités de genre",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "Philcarto, Inkscape",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux de chômage féminin (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le chômage féminin est systématiquement supérieur au chômage masculin dans toutes les provinces. Il atteint des niveaux critiques dans les zones urbaines où les femmes diplômées peinent à s'insérer sur le marché du travail.",
    imageFilename: "Taux_chomage_Feminin_pct.jpg",
  },
  {
    key: "chomage_masculin",
    titre: "Taux de chômage masculin par province",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Chômage masculin",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "Philcarto, Inkscape",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux de chômage masculin (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le chômage masculin suit une distribution spatiale similaire au chômage général, avec une concentration dans les zones urbaines. Berrechid et Médiouna, en périphérie de Casablanca, présentent des taux intermédiaires liés à leur profil industriel en mutation.",
    imageFilename: "Taux_chomage_Hommes_pct.jpg",
  },
  {
    key: "ecart_chomage_fh",
    titre: "Écart du taux de chômage Femmes / Hommes",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Inégalités de genre dans le chômage",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS / Philcarto",
    typeRepresentation: "Carte choroplèthe (valeurs différentielles)",
    variableRepresentee: "Écart en points de % entre chômage féminin et masculin",
    natureInformation: "Quantitative relative différentielle",
    messagePrincipal:
      "L'écart de chômage entre femmes et hommes dépasse 10 points dans plusieurs provinces. Cet écart est plus marqué en milieu urbain qu'en milieu rural, où le faible taux d'activité féminine masque en partie la réalité du sous-emploi.",
    imageFilename: "Ecart_FH_chomage.jpg",
  },
  {
    key: "taux_activite",
    titre: "Taux d'activité économique par province",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Taux d'activité économique",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Taux d'activité de la population en âge de travailler (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Le taux d'activité est plus élevé dans les provinces industrielles (Berrechid, Mohammedia). Les zones rurales comme Sidi Bennour affichent des taux plus faibles, liés à la saisonnalité agricole et au faible taux d'activité féminine.",
    imageFilename: "Taux d'activité par province.jpg",
  },
  {
    key: "activite_genre",
    titre: "Taux d'activité économique Hommes / Femmes",
    categorie: "Emploi & Activité",
    theme: "Emploi — Marché du travail",
    sousTheme: "Inégalités de genre dans l'activité économique",
    source: "HCP — RGPH 2014",
    annee: "2014",
    logiciel: "QGIS / Philcarto",
    typeRepresentation: "Carte comparative bipartite",
    variableRepresentee: "Taux d'activité masculin · Taux d'activité féminin",
    natureInformation: "Quantitative relative comparée",
    messagePrincipal:
      "L'écart d'activité entre hommes et femmes est particulièrement prononcé : le taux d'activité masculin dépasse 70% dans la plupart des provinces, tandis que le taux féminin reste inférieur à 25% dans les zones rurales, révélant une forte inégalité de genre dans l'emploi.",
    imageFilename: "Carte activité Hommes Femmes.jpg",
  },
  {
    key: "employes_repartition",
    titre: "Répartition des employés dans la région",
    categorie: "Emploi & Activité",
    theme: "Emploi — Répartition spatiale",
    sousTheme: "Densité des employés territoriale",
    source: "HCP — Annuaire statistique 2018",
    annee: "2015–2017",
    logiciel: "Philcarto, Inkscape",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Densité des employés (indice normalisé)",
    natureInformation: "Quantitative relative (indice)",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "La densité d'employés est massivement concentrée dans la préfecture de Casablanca, qui totalise plus de 65% des employés régionaux. Berrechid et Mohammedia se démarquent comme pôles industriels secondaires avec une densité d'employés notable.",
    imageFilename: "employes.pdf",
  },

  // ─── ÉCONOMIE ──────────────────────────────────────────────────────────────
  {
    key: "etablissements_nb",
    titre: "Nombre d'établissements économiques par province",
    categorie: "Économie",
    theme: "Économie — Structure productive",
    sousTheme: "Répartition spatiale des établissements économiques",
    source: "HCP — Annuaire statistique 2018",
    annee: "2015–2017",
    logiciel: "QGIS",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Nombre d'établissements économiques",
    natureInformation: "Quantitative absolue",
    messagePrincipal:
      "Plus de 60% des établissements économiques de la région sont concentrés dans la préfecture de Casablanca. Cette hyper-concentration crée des effets d'agglomération mais génère aussi d'importants déséquilibres territoriaux entre le centre métropolitain et la périphérie.",
    imageFilename: "Nombre d'établissements.jpg",
  },
  {
    key: "industrie_cercles",
    titre: "Établissements industriels et part de l'industrie",
    categorie: "Économie",
    theme: "Économie — Structure productive",
    sousTheme: "Spécialisation industrielle territoriale",
    source: "HCP — Annuaire statistique 2018",
    annee: "2015–2017",
    logiciel: "Philcarto, Inkscape",
    typeRepresentation: "Carte à cercles proportionnels (nombre d'établissements) + choroplèthe (% industrie)",
    variableRepresentee: "Nombre total d'établissements (cercles) · Part du secteur industriel (couleur)",
    natureInformation: "Quantitative absolue + relative",
    messagePrincipal:
      "Si Casablanca domine en nombre absolu d'établissements, Berrechid et Médiouna se distinguent par une part relative de l'industrie plus élevée, reflétant leur profil de zones industrielles périurbaines. Cette carte illustre la diversification économique progressive de la périphérie casablancaise.",
    imageFilename: "CerclesPropo[Nb_etab_total][pct_industrie]inscape.jpg",
  },
  {
    key: "economie_ca_industrie",
    titre: "Chiffre d'affaires et établissements industriels",
    categorie: "Économie",
    theme: "Économie — Structure productive",
    sousTheme: "Performance économique industrielle",
    source: "HCP — Annuaire statistique 2018",
    annee: "2015–2017",
    logiciel: "Philcarto, Inkscape",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte choroplèthe + cercles proportionnels",
    variableRepresentee: "Chiffre d'affaires (Mdh) · Nombre d'établissements industriels",
    natureInformation: "Quantitative monétaire + absolue",
    methodDiscretisation: "Normalisation, seuils naturels (Jenks)",
    messagePrincipal:
      "Casablanca génère un chiffre d'affaires industriel qui dépasse 172 milliards de dirhams, soit plus de 80% du total régional. L'écart avec les autres provinces est considérable, Mohammedia et Berrechid occupant une position secondaire grâce à leurs zones industrielles.",
    imageFilename: "economie.pdf",
  },

  // ─── TERRITOIRE & URBAIN ───────────────────────────────────────────────────
  {
    key: "huff_gravitation",
    titre: "Gravitation urbaine — Modèle de Huff",
    categorie: "Territoire & Urbain",
    theme: "Territoire — Organisation spatiale",
    sousTheme: "Aires d'attraction des pôles urbains",
    source: "HCP — RGPH 2024",
    annee: "2024",
    logiciel: "Python (pandas, numpy) + QGIS 3.x",
    typeRepresentation: "Carte de synthèse — plages de couleur par pôle dominant",
    classification: "Carte analytique — modèle d'interaction spatiale",
    variableRepresentee: "Pôle dominant par province (modèle de Huff) · Indice d'attractivité Aj (cercles proportionnels)",
    natureInformation: "Qualitative nominale + quantitative relative (indice)",
    constructionIndice: "Modèle de Huff : P(i→j) = [Aj^α / d_ij^β] / Σk [Ak^α / d_ik^β] · α=1, β=2 · Distances Haversine",
    messagePrincipal:
      "Casablanca exerce une domination gravitationnelle écrasante : 6 provinces sur 9 lui sont rattachées, dont Sidi Bennour pourtant à 134 km. El Jadida (99,79%), Mohammedia (91,83%) et Settat (87,47%) maintiennent leur autonomie grâce à l'éloignement ou à leur masse économique propre.",
    imageFilename: "Carte_Huff_Gravitation.png",
  },
  {
    key: "typologie_provinces",
    titre: "Typologie des provinces de la région",
    categorie: "Territoire & Urbain",
    theme: "Territoire — Organisation spatiale",
    sousTheme: "Typologie territoriale multi-critères",
    source: "HCP — RGPH 2014 + Annuaire statistique",
    annee: "2014–2017",
    logiciel: "QGIS / R",
    typeRepresentation: "Carte choroplèthe typologique",
    classification: "Carte de synthèse — classification multivariée",
    variableRepresentee: "Profil composite multi-critères (démographie, économie, urbanisation)",
    natureInformation: "Qualitative nominale (typologie)",
    methodDiscretisation: "Classification ascendante hiérarchique (CAH)",
    messagePrincipal:
      "La classification révèle trois profils dominants : la métropole (Casablanca), les pôles industriels périurbains (Berrechid, Mohammedia, Médiouna), et les provinces agro-rurales (Sidi Bennour, Settat, El Jadida). Cette structuration guide les priorités d'aménagement territorial de la région.",
    imageFilename: "Carte_Typologie_Provinces.png",
  },
  {
    key: "synthese",
    titre: "Carte de synthèse régionale",
    categorie: "Territoire & Urbain",
    theme: "Territoire — Synthèse régionale",
    sousTheme: "Synthèse multi-dimensionnelle du territoire",
    source: "HCP — RGPH 2024 + Annuaires statistiques",
    annee: "2024",
    logiciel: "QGIS + Inkscape",
    typeRepresentation: "Carte de synthèse multi-couches",
    classification: "Carte de synthèse — multi-couches thématiques",
    variableRepresentee: "Indicateurs démographiques, économiques et territoriaux combinés",
    natureInformation: "Mixte (multi-dimensionnelle)",
    messagePrincipal:
      "Cette carte de synthèse combine les principales dimensions du territoire régional : structure urbaine, activité économique et organisation spatiale. Elle illustre les déséquilibres structurels entre le pôle métropolitain de Casablanca et les espaces périphériques de la région.",
    imageFilename: "mise en page  de carte de synthèse.png",
  },
  {
    key: "flux_liens_casa",
    titre: "Liens et flux de mobilité — Région Casablanca-Settat",
    categorie: "Territoire & Urbain",
    theme: "Territoire — Mobilité et flux",
    sousTheme: "Flux de mobilité inter-provinciaux",
    source: "HCP — RGPH 2024",
    annee: "2024",
    logiciel: "QGIS / Python",
    typeRepresentation: "Carte en oursins (flux orientés)",
    variableRepresentee: "Intensité et direction des flux de mobilité entre provinces",
    natureInformation: "Quantitative relative (flux) + orientation",
    messagePrincipal:
      "La carte en oursins révèle que Casablanca est le pôle attracteur dominant de tous les flux de mobilité régionaux. Les flux les plus intenses convergent depuis Berrechid, Médiouna et Nouaceur, soulignant le rôle structurant de la métropole dans l'organisation des déplacements pendulaires.",
    imageFilename: "Liens_oursins_Casa.png",
  },
  {
    key: "flux_mobilite_2024",
    titre: "Intensité de mobilité — Région Casablanca-Settat",
    categorie: "Territoire & Urbain",
    theme: "Territoire — Mobilité et flux",
    sousTheme: "Intensité des flux de mobilité",
    source: "HCP — RGPH 2024",
    annee: "2024",
    logiciel: "QGIS / Python",
    typeRepresentation: "Carte de flux et d'intensité de mobilité",
    variableRepresentee: "Volume et intensité des flux de déplacement entre communes/provinces",
    natureInformation: "Quantitative relative (intensité des flux)",
    messagePrincipal:
      "Les flux de mobilité inter-provinciaux se structurent autour de Casablanca, qui polarise l'essentiel des déplacements régionaux. L'axe Casablanca–Berrechid–Settat est le couloir de mobilité le plus actif, suivi de l'axe littoral Casablanca–Mohammedia.",
    imageFilename: "carte_flux_casablanca.pdf",
  },

  // ─── ACCIDENTS & MOBILITÉ ──────────────────────────────────────────────────
  {
    key: "accidents_total_semis",
    titre: "Répartition des accidents de la route — Semis de points",
    categorie: "Accidents & Mobilité",
    theme: "Mobilité — Sécurité routière",
    sousTheme: "Densité spatiale des accidents",
    source: "HCP — Annuaire statistique 2018",
    annee: "2016",
    logiciel: "QGIS",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte en densité de points (1 point = 50 accidents)",
    variableRepresentee: "Nombre d'accidents par localisation",
    natureInformation: "Quantitative absolue (densité de points)",
    methodDiscretisation: "Seuils naturels (Jenks) · 1 point = 50 accidents",
    messagePrincipal:
      "La densité d'accidents est maximale dans l'agglomération de Casablanca et sur les axes routiers principaux (A1, A3, A5). Les zones rurales enregistrent moins d'accidents en nombre absolu mais des taux de gravité souvent plus élevés liés à la vitesse excessive.",
    imageFilename: "C1B_Semis_points_colores.jpg",
  },
  {
    key: "accidents_total_choro",
    titre: "Répartition des accidents de la route — Choroplèthe",
    categorie: "Accidents & Mobilité",
    theme: "Mobilité — Sécurité routière",
    sousTheme: "Répartition provinciale des accidents",
    source: "HCP — Annuaire statistique 2018",
    annee: "2016",
    logiciel: "QGIS",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte choroplèthe",
    variableRepresentee: "Part provinciale des accidents (%)",
    natureInformation: "Quantitative relative",
    methodDiscretisation: "Seuils naturels (Jenks)",
    messagePrincipal:
      "Casablanca concentre plus de 40% des accidents de la région, suivie par Settat et El Jadida. Cette répartition reflète à la fois la densité du trafic et la longueur du réseau routier par province.",
    imageFilename: "total acd.pdf",
  },
  {
    key: "accidents_type_usager",
    titre: "Victimes d'accidents selon le type d'usager",
    categorie: "Accidents & Mobilité",
    theme: "Mobilité — Sécurité routière",
    sousTheme: "Vulnérabilité des usagers de la route",
    source: "HCP — Annuaire statistique 2018",
    annee: "2016",
    logiciel: "QGIS",
    auteur: "El Afia Mohamed",
    typeRepresentation: "Carte à cercles proportionnels avec diagrammes en secteurs",
    variableRepresentee: "Nombre de victimes (cercles) · Type d'usager (secteurs : piétons, véhicules légers, motos…)",
    natureInformation: "Quantitative absolue + relative (proportions)",
    messagePrincipal:
      "Les piétons et les deux-roues sont les usagers les plus vulnérables, représentant plus de 50% des victimes dans les zones urbaines. En milieu rural, les accidents de véhicules légers à haute vitesse dominent, avec une mortalité proportionnellement plus élevée.",
    imageFilename: "sln-type-usager-camembert.pdf",
  },

  // ─── ENVIRONNEMENT ─────────────────────────────────────────────────────────
  {
    key: "precipitation",
    titre: "Précipitations dans la région Casablanca-Settat",
    categorie: "Environnement",
    theme: "Environnement — Climat",
    sousTheme: "Gradient pluviométrique régional",
    source: "Direction de la Météorologie Nationale (DMN)",
    annee: "Moyenne pluriannuelle",
    logiciel: "QGIS",
    typeRepresentation: "Carte isohuète / choroplèthe",
    variableRepresentee: "Précipitations annuelles moyennes (mm)",
    natureInformation: "Quantitative absolue",
    messagePrincipal:
      "La région présente un gradient pluviométrique nord-sud : le littoral atlantique reçoit entre 350 et 500 mm/an grâce à l'influence océanique, tandis que les zones intérieures (Settat, Sidi Bennour) sont soumises à une semi-aridité avec moins de 300 mm/an. Ce gradient conditionne les pratiques agricoles et les ressources en eau.",
    imageFilename: "precipitation.pdf",
  },
  {
    key: "idse_synthese",
    titre: "Indice de développement socio-économique par province et préfecture",
    sousTitre: "Indice composite : urbanisation, analphabétisme, chômage, IPM, habitat et établissements/1000 hab. (2024)",
    categorie: "Social & Éducation",
    theme: "Développement territorial / Synthèse socio-économique",
    sousTheme: "Niveau relatif de développement socio-économique",
    source: "RGPH 2024, HCP ; Activité économique Philcarto ; BDR Établissements économiques",
    annee: "2024",
    logiciel: "Philcarto (choroplèthe) + Inkscape (mise en page)",
    typeRepresentation: "Carte choroplèthe - synthèse composite (IDSE)",
    classification: "Carte analytique issue d'un indice composite",
    variableRepresentee: "Indice de développement socio-économique (0-100)",
    natureInformation: "Quantitative relative ordonnée (indice composite)",
    constructionIndice: "Composantes favorables (+) : taux d'urbanisation, % ménages propriétaires, établissements/1 000 hab. · Composantes défavorables (-) : taux d'analphabétisme, taux de chômage, IPM · Normalisation min-max de chaque indicateur, inversion des variables défavorables, moyenne des 6 scores × 100",
    formule: "IDSE = moyenne(N_urb, N_prop, N_etab, N_analph, N_chom, N_ipm) × 100",
    methodDiscretisation: "Jenks (seuils naturels) - 4 classes",
    nombreClasses: 4,
    classesValeurs: "Faible [19-35] · Moyen [35-48] · Élevé [48-63] · Très élevé [63-72]",
    statsDescriptives: "Min : 19,05 (Sidi Bennour) · Max : 72,22 (Casablanca) · Moyenne : 48,16 · Écart-type : 18,75 · CV : 38,9%",
    messagePrincipal: "La région présente une forte différenciation intra-régionale du développement socio-économique. Casablanca domine avec un IDSE de 72, tandis que Sidi Bennour cumule les déficits structurels (IDSE 19). Les provinces périurbaines (Médiouna, Nouaceur) occupent une position intermédiaire grâce à leur dynamique industrielle.",
    limites: "L'indice est une simplification synthétique ; les six composantes ont le même poids ; les résultats varient selon la méthode de discrétisation.",
    imageFilename: "Synthèse_IDSE_emf.jpg",
  },
  {
    key: "indice_sanitaire",
    titre: "Indice d'équipement sanitaire par province et préfecture",
    sousTitre: "Médecins, lits hospitaliers et ESSB pour 10 000 habitants (2021-2024)",
    categorie: "Social & Éducation",
    theme: "Santé - Équipements sanitaires",
    sousTheme: "Indice composite d'équipement de santé (médecins, hôpitaux, ESSB)",
    source: "RGPH 2024 (HCP) · BDR Santé MSPS 2021 (médecins, ESSB) · BDR Santé MSPS 2023 (lits hospitaliers)",
    annee: "2021-2024",
    logiciel: "Philcarto (choroplèthe) + Inkscape (mise en page)",
    typeRepresentation: "Carte choroplèthe",
    classification: "Carte de synthèse - indice composite de 3 indicateurs normalisés",
    variableRepresentee: "Indice d'équipement sanitaire (0-100)",
    natureInformation: "Quantitative relative ordonnée (indice composite)",
    constructionIndice: "3 ratios normalisés par le maximum régional : médecins/10 000 hab. · lits hospitaliers/10 000 hab. · ESSB/10 000 hab. · Moyenne des 3 scores × 100",
    methodDiscretisation: "Jenks (seuils naturels) - 4 classes",
    nombreClasses: 4,
    classesValeurs: "Faible [21-27] : Nouaceur, Sidi Bennour · Moyen [37-38] : Berrechid, El Jadida, Mohammedia · Élevé [44-48] : Médiouna, Settat, Benslimane · Très élevé [94] : Casablanca",
    statsDescriptives: "Min : 21,2 (Nouaceur) · Max : 93,8 (Casablanca) · Moyenne : 43,3 · CV : 45% · Distribution très asymétrique - Casablanca valeur atypique",
    messagePrincipal: "La région présente de fortes inégalités sanitaires. Casablanca concentre l'essentiel des équipements (indice 93,8) grâce aux CHU et cliniques privées. Nouaceur et Sidi Bennour souffrent d'un déficit structurel malgré leur croissance démographique. Un groupe intermédiaire (Berrechid, El Jadida, Mohammedia) présente des dotations modestes mais homogènes.",
    limites: "L'indice agrège médecins publics et privés, masquant l'accès réel des populations à faible revenu. Les 3 indicateurs ont le même poids. Les données médecins (2021) et lits (2023) ne sont pas synchrones.",
    imageFilename: "synthèse_Indice_sanitaire.jpg",
  },
  {
    key: "pression_eau",
    titre: "Pression sur l'eau potable par province et préfecture",
    sousTitre: "Indice composite : volume distribué, m³/habitant, évolution 2015-2019",
    categorie: "Environnement",
    theme: "Ressources hydriques / Eau potable",
    sousTheme: "Pression territoriale sur l'eau potable",
    source: "BDR Eau Potable MSPS 2015-2019 · RGPH 2024 (HCP)",
    annee: "2015-2019",
    logiciel: "Philcarto (choroplèthe) + Inkscape (mise en page)",
    typeRepresentation: "Carte choroplèthe avec histogramme annexe de classement provincial",
    classification: "Carte de synthèse - indice composite de 3 indicateurs normalisés",
    variableRepresentee: "Indice de pression sur l'eau potable (0-100)",
    natureInformation: "Quantitative relative ordonnée (indice composite)",
    constructionIndice: "Volume d'eau potable distribué (×10³ m³) · Consommation moyenne par habitant (m³/hab/an) · Évolution du volume distribué 2015-2019 (%) · Normalisation min-max de chaque indicateur, moyenne des 3 × 100",
    methodDiscretisation: "Jenks (seuils naturels) - 4 classes",
    nombreClasses: 4,
    classesValeurs: "Faible [19,8-20,0] : Sidi Bennour, Berrechid · Modérée [25,2-27,4] : Settat, Mohammedia, El Jadida · Élevée [33,3-36,4] : Benslimane, Médiouna · Très forte [59,8-67,3] : Nouaceur, Casablanca",
    statsDescriptives: "Min : 19,81 (Sidi Bennour) · Max : 67,28 (Casablanca) · Moyenne : 35,12 · CV : 48,6% · Distribution asymétrique positive",
    messagePrincipal: "La pression sur l'eau potable est très inégalement répartie. Casablanca (67,3) et Nouaceur (59,8) forment un noyau de très forte pression en raison de volumes distribués élevés et d'une consommation soutenue par habitant. À l'inverse, Berrechid et Sidi Bennour restent en situation de faible pression, tandis que Settat, El Jadida et Mohammedia occupent une position intermédiaire.",
    limites: "Les séries annuelles sont incomplètes pour plusieurs provinces. L'indice mesure une pression potentielle, non la disponibilité physique de la ressource. La population utilisée (2024) n'est pas synchrone avec les volumes (2015-2019).",
    imageFilename: "Carte_Indice_pression_eau.jpg",
  },
];

export const CATEGORIES: Categorie[] = [
  "Démographie",
  "Social & Éducation",
  "Emploi & Activité",
  "Économie",
  "Territoire & Urbain",
  "Accidents & Mobilité",
  "Environnement",
];

export const CATEGORY_COLORS: Record<Categorie, string> = {
  "Démographie": "#3B82F6",
  "Social & Éducation": "#8B5CF6",
  "Emploi & Activité": "#F59E0B",
  "Économie": "#10B981",
  "Territoire & Urbain": "#EF4444",
  "Accidents & Mobilité": "#F97316",
  "Environnement": "#06B6D4",
};

export const CATEGORY_ICONS: Record<Categorie, string> = {
  "Démographie": "👥",
  "Social & Éducation": "🎓",
  "Emploi & Activité": "💼",
  "Économie": "📊",
  "Territoire & Urbain": "🏙️",
  "Accidents & Mobilité": "🚦",
  "Environnement": "🌍",
};
